apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sandbox
  name: techtrends
  labels:
    app: techtrends
    tag: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image: zaomai/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
